### ISSUE TITLE
Feature request: add a way to save the figure as a png/pdf/... file

### ISSUE THREAD

**Issue by durandg12** [AndreasMadsen/python-lrcurve#1]
Hello, it would be nice to have a `filepath` argument in the class constructor that allows the final figure to be saved as an image file (a png, or a pdf, or a jpeg, etc). Or maybe there is already a way to extract it from the notebook and to save it by manipulating IPython?

**Comment by AndreasMadsen** [comment]
The graph is rendered in the browser using SVG (not PNG, PDF, or JPEG). The SVG could, in theory, be saved but you would then have to convert it. LaTeX, Word, Google Docs, etc. does not support SVG.

To save it as a PNG, PDF, or JPEG, it would have to be rendered using a completely different engine, so it would look rather different.

If you have a more concrete suggestion on how to do this, that isn't extremely complex, then we can consider it.

**Comment by ghost** [comment]
Maybe [canvg](https://github.com/canvg/canvg) can help. It uses `canvas` under-the-hood, thus you can [export](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) the final output as PNG, JPEG or WEBP (depending on the web browser).

**Comment by AndreasMadsen** [comment]
I have now investigated this thoroughly. Unfortunately communicating from JavaScript to Python, the way that would be required for this, appears to be difficult. As far as I understand `IPython.notebook.kernel.execute` does no longer exist, but instead the iPython-widget system has to be used. This, unfortunately, has its own challenges.

I would suggest you simply use ggplot2 equivalent, like ggplot or plotnine for python, if it is the style you like.
