### ISSUE TITLE
Issue during importing

### ISSUE THREAD

**Issue by joaocmd** [AndreasMadsen/python-lrcurve#11]
Sorry if the title does not seem like much. I tried using your package in a python notebook and couldn't use the `append` method, which was trying to get `.items()` over the `y` values.

This [other repository](https://github.com/lvwerra/jupyterplot/blob/master/jupyterplot/jupyterplot.py#L9) seems to have the same issue and came with a hack to fix it, and it also worked in my Colab notebook.

**Comment by AndreasMadsen** [comment]
The issue in the link you reference was solved in https://github.com/AndreasMadsen/python-lrcurve/commit/0edbc25405e801ab2901fe336f3c464f9102fdc7

I don't see any relation to the first-mentioned issue. You will have to provide a reproducible example.

**Comment by joaocmd** [comment]
When running a clean notebook, the issue does not happen. It was probably due to having imported the other package first. Seems like everything works as expected, thanks 👍 .

**Comment by AndreasMadsen** [comment]
No problem
