### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by iamgroot42** [AndreasMadsen/python-lrcurve#2]
I tried using this package on a Windows machine on Jupyter (python 3.7.4, 64 bit) and faced the following issue when trying out the dummy example:

![image](https://user-images.githubusercontent.com/10141323/70860934-7a1ec080-1f4d-11ea-914c-257292fbabd1.png)

**Comment by AndreasMadsen** [comment]
Thanks. I can't reproduce it but I suspect it is the non-ascii chars in the bundle that d3 ships. They are only used in comments so I used iconv to strip them from the code.

Can you try `lrcurve` version `1.0.2`?
