### ISSUE TITLE
Plotting broken in TensorFlow 2.2

### ISSUE THREAD

**Issue by DJCordhose** [AndreasMadsen/python-lrcurve#4]
TF 2.2 changed its API so that metrics_names are only available *after* the model  has been
trained/evaluated on actual data.

the `on_train_begin` callback tries to use that information, but since it is the beginning of the training, those metrics are not there, yet. 

this is the error you will get

```
<ipython-input-18-782c326bcb7b> in on_train_begin(self, logs)
     55         if self._metric_mapping is None:
     56             self._metric_mapping = {}
---> 57             for metric_name in self.params['metrics']:
     58                 if self.params['do_validation'] and metric_name.startswith('val_'):
     59                     self._metric_mapping[metric_name] = {

KeyError: 'metrics'
```

**Comment by DJCordhose** [comment]
This might actually not be quite accurate, it seems in on_train_begin self.params does not contain anything interesting any more. When logging it, I see:

> {'verbose': 0, 'epochs': 1000, 'steps': 13}

but nothing like `do_validation` or the other entries expected in the code.

This definitely works in 2.1

**Comment by DJCordhose** [comment]
Additionally, logs only contains the current metrics when **on_epoch_end** is called.

**Comment by AndreasMadsen** [comment]
Yeah, I found the same issue. It might be a bug in kreas. I will investigate some more.

**Comment by DJCordhose** [comment]
I am afraid it is not a bug, but the result of a general internal re-design which broke Keras' callback API (which was pretty much unspecified before, so we can not technically say, it is broken).

**Comment by AndreasMadsen** [comment]
Should be fixed now in version 1.1.1.

**Comment by DJCordhose** [comment]
I can confirm it works in 2.2.0 now, thanks a lot for the fix

also looked at the code: smart way to fix it

kudos for both

**Comment by AndreasMadsen** [comment]
This fix do have the downside that the plot isn't rendered until the end of the first epoch.

**Comment by DJCordhose** [comment]
I saw that, but since until then there simply is nothing to render in 2.2,
I see no better solution.

**Comment by DJCordhose** [comment]
or maybe the information is already there after first batch?
