### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'mappings'

### ISSUE THREAD

**Issue by jagjeet-singh** [AndreasMadsen/python-lrcurve#6]
Hi, thanks for creating this library. It's very useful.

Was there a recent change which is breaking things? I run the `PyTorch example` mentioned on the README. It used to work fine last time I tried (more than a month back). Now it breaks with the error
```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-ea9466af3eee> in <module>
     12         'acc': { 'name': 'Accuracy', 'limit': [0, 1], 'scale': 'linear' }
     13     },
---> 14     xaxis_config = { 'name': 'Epoch', 'limit': [0, 500] }
     15 )
     16 

TypeError: __init__() got an unexpected keyword argument 'mappings'
```

**Comment by kevinwu23** [comment]
Same issue here...

**Comment by AndreasMadsen** [comment]
Sorry, I tried to reproduce this issue today but couldn't. Please submit a Google Colab etc. The Google Colab link in the README works: https://colab.research.google.com/github/AndreasMadsen/python-lrcurve/blob/master/notebooks/pytorch_example.ipynb

**Comment by AndreasMadsen** [comment]
No response, I assume you were using an old version of lrcurve. I'm closing issue.
