### ISSUE TITLE
Callback for xgboost

### ISSUE THREAD

**Issue by bhishanpdl** [AndreasMadsen/python-lrcurve#7]
Feature Request:
Xgboost is one of the most used module in machine learning like keras in deep learning. There is built-in callback for keras, I would like to suggest that please make callback for the xgboost model.

**Comment by AndreasMadsen** [comment]
You could also write your own module that depends on lrcurve, and just treat KerasLearningCurve as an example of how to implement it.

I'm definitely not going to implement it myself, I **may** consider it if a PR is made.

**Comment by bhishanpdl** [comment]
Thanks for the heads up. I will try to follow the example of KerasLearningCurve.
